### Site info:
title: Ke YAN's blog
tagline: Postdoc @ NIH, US
author: YAN Ke
email: yankethu &lt;at&gt; foxmail.com
description: "A personal website."
keywords: "research, programming, blog"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yanke23.com" # the base hostname & protocol for your site
locale: en_US

### Personal info and site tools info:
CSDN_username: viggin
Mathworks_username: 2503880-edward-wiggin
github_username: viggin
weibo_username: 2619635890
disqus_shortname: yanke23
favicon:     "/images/icoyk.png"
aboutme: Please contact me via # these are shown on aboutme-sidebar.
aboutme_photo: /images/aboutme.jpg # your photo.


### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown when ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "en" # blog sidebar language set, only include: English(en) and Chinese (cn)

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"  
      PostDate: "on "
    cn:
      Aboutme: "关于我"
      Archives: "存档"
      Blogroll: "良师益友"        
      Categories: "分类目录"    
      Copyright_Notice: "版权声明"
      Recent_Posts: "近期文章"
      Tags: "标签" 
      Previous: "前一页"
      Next: "后一页"
      PostedInCategories: "目录:"   
      Taggedwith: "| 标签:"
      PostDate: "| 发表时间: "


### your Blogroll info, only name can shown on the page.

Blogroll:
    - name: Freshman21
      href: http://yulijia.net/freshman21
      title: Another Jekyll blog theme
    - name: Prof. David Zhang
      href: http://www4.comp.polyu.edu.hk/~csdzhang/
      title: Prof. David Zhang
    - name: 多才多艺的师兄
      href: http://www.quxiaofeng.me/
      title: Xiaofeng Qu
    - name: 学术牛人师兄
      href: http://www.leizhang.tk/
      title: Lei Zhang


### Build settings
markdown: kramdown
highlighter: pygments
paginate: 5
excerpt_separator: <!-- more -->
gems: [jekyll-paginate]
port: 1357